"""Initial multilingual dream-symbol catalogue.

The descriptions are concise paraphrases prepared for application use. They
are interpretive leads, not quotations or deterministic definitions. Jungian
entries must always be combined with the dreamer's personal associations and
the complete dream context.
"""

MYSTICAL_BOOK = "O Livro dos Sonhos - L. P. Baçan"
JUNG_BOOK = "O Homem e seus Símbolos - C. G. Jung et al."


def _entry(
    key: str,
    names: tuple[str, str, str],
    meanings: tuple[str, str, str],
    interpretation_type: str,
    tradition: str,
    source_book: str,
    source_reference: str,
    context_note_pt: str | None = None,
) -> dict:
    return {
        "canonical_key": key,
        "name_pt": names[0], "name_en": names[1], "name_es": names[2],
        "meaning_pt": meanings[0], "meaning_en": meanings[1], "meaning_es": meanings[2],
        "interpretation_type": interpretation_type,
        "tradition": tradition,
        "source_book": source_book,
        "source_reference": source_reference,
        "context_note_pt": context_note_pt,
    }


INITIAL_DREAM_SYMBOLS = (
    _entry("bee", ("Abelha", "Bee", "Abeja"),
           ("Associa-se a oportunidades financeiras e a surpresas na vida amorosa.", "Associated with financial opportunities and surprises in love.", "Se asocia con oportunidades financieras y sorpresas en el amor."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 6"),
    _entry("abyss", ("Abismo", "Abyss", "Abismo"),
           ("Sugere hostilidade ao redor e incerteza nos vínculos afetivos.", "Suggests surrounding hostility and uncertainty in emotional bonds.", "Sugiere hostilidad alrededor e incertidumbre en los vínculos afectivos."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 6"),
    _entry("water", ("Água", "Water", "Agua"),
           ("Indica paz e harmonia na vida, além de fidelidade no amor.", "Indicates peace and harmony in life, along with fidelity in love.", "Indica paz y armonía en la vida, además de fidelidad en el amor."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 11"),
    _entry("tree", ("Árvore", "Tree", "Árbol"),
           ("Relaciona-se a solidez, paz e estabilidade afetiva.", "Relates to solidity, peace and emotional stability.", "Se relaciona con solidez, paz y estabilidad afectiva."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 20"),
    _entry("house", ("Casa", "House", "Casa"),
           ("Aponta para felicidade e desejo de união.", "Points to happiness and a desire for union.", "Apunta a felicidad y deseo de unión."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 46"),
    _entry("horse", ("Cavalo", "Horse", "Caballo"),
           ("Adverte sobre amizades pouco confiáveis e insatisfação afetiva.", "Warns of unreliable friendships and emotional dissatisfaction.", "Advierte sobre amistades poco fiables e insatisfacción afectiva."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 47"),
    _entry("snake", ("Cobra", "Snake", "Serpiente"),
           ("É associada a problemas e insatisfação nos relacionamentos.", "Associated with problems and dissatisfaction in relationships.", "Se asocia con problemas e insatisfacción en las relaciones."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 53"),
    _entry("fire", ("Fogo", "Fire", "Fuego"),
           ("Sinaliza risco de perda profissional e ciúmes na esfera afetiva.", "Signals risk of professional loss and jealousy in emotional life.", "Señala riesgo de pérdida profesional y celos en la vida afectiva."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 84"),
    _entry("moon", ("Lua", "Moon", "Luna"),
           ("Relaciona-se a ambição e a possibilidades de felicidade e realização amorosa.", "Relates to ambition and possibilities of happiness and fulfillment in love.", "Se relaciona con ambición y posibilidades de felicidad y realización amorosa."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 108"),
    _entry("sea", ("Mar", "Sea", "Mar"),
           ("Sugere sobrecarga de trabalho e intrigas na vida amorosa.", "Suggests work overload and intrigue in love life.", "Sugiere exceso de trabajo e intrigas en la vida amorosa."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 112"),
    _entry("death", ("Morte", "Death", "Muerte"),
           ("Representa mudança e a chegada de novidades na esfera afetiva.", "Represents change and new developments in emotional life.", "Representa cambio y la llegada de novedades en la vida afectiva."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 119"),
    _entry("bird", ("Pássaro", "Bird", "Pájaro"),
           ("Relaciona sofrimento moral na vida a uma tendência de tranquilidade no amor.", "Links moral distress in life with a tendency toward tranquility in love.", "Relaciona sufrimiento moral en la vida con una tendencia a la tranquilidad en el amor."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 130"),
    _entry("stone", ("Pedra", "Stone", "Piedra"),
           ("Associa-se a questões judiciais e sofrimento afetivo.", "Associated with legal matters and emotional suffering.", "Se asocia con asuntos judiciales y sufrimiento afectivo."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 131"),
    _entry("sun", ("Sol", "Sun", "Sol"),
           ("Indica melhora financeira acompanhada de preocupações amorosas.", "Indicates financial improvement accompanied by concerns in love.", "Indica mejora financiera acompañada de preocupaciones amorosas."),
           "MYSTICAL", "POPULAR_ESOTERIC", MYSTICAL_BOOK, "PDF p. 153"),

    _entry("water", ("Água", "Water", "Agua"),
           ("Pode figurar conteúdos emocionais e inconscientes nos quais o ego entra ou dos quais tenta se proteger.", "May portray emotional and unconscious contents that the ego enters or tries to avoid.", "Puede representar contenidos emocionales e inconscientes en los que el yo entra o de los que intenta protegerse."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 24-25, 212",
           "Interpretar conforme a forma da água, ao movimento e às associações pessoais do sonhador."),
    _entry("tree", ("Árvore", "Tree", "Árbol"),
           ("Pode expressar vida, enraizamento, crescimento e o desenvolvimento orgânico da personalidade.", "May express life, rootedness, growth and the organic development of personality.", "Puede expresar vida, arraigo, crecimiento y desarrollo orgánico de la personalidad."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 23, 79-80",
           "A árvore também pode assumir sentidos culturais, religiosos ou estritamente pessoais."),
    _entry("house", ("Casa", "House", "Casa"),
           ("Frequentemente oferece uma imagem da própria psique; cômodos e níveis podem representar áreas conhecidas ou desconhecidas da personalidade.", "Often offers an image of the psyche itself; rooms and levels may represent known or unknown areas of personality.", "A menudo ofrece una imagen de la propia psique; habitaciones y niveles pueden representar áreas conocidas o desconocidas de la personalidad."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 26-27, 56",
           "Não presumir equivalência fixa entre um cômodo e uma função psíquica."),
    _entry("snake", ("Cobra", "Snake", "Serpiente"),
           ("Pode constelar instinto, energia subterrânea, sabedoria, perigo ou transformação, conforme a ação da serpente e a resposta do sonhador.", "May constellate instinct, chthonic energy, wisdom, danger or transformation, depending on the snake's action and the dreamer's response.", "Puede constelar instinto, energía ctónica, sabiduría, peligro o transformación, según la acción de la serpiente y la respuesta del soñante."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 34, 78, 96",
           "A ambivalência é essencial: ameaça e potência transformadora podem coexistir."),
    _entry("sun", ("Sol", "Sun", "Sol"),
           ("Pode simbolizar consciência, energia vivificante, centralidade e uma experiência do sagrado.", "May symbolize consciousness, life-giving energy, centrality and an experience of the sacred.", "Puede simbolizar conciencia, energía vivificante, centralidad y una experiencia de lo sagrado."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 20-21",
           "O sentido depende da tradição cultural e da experiência subjetiva evocada."),
    _entry("stone", ("Pedra", "Stone", "Piedra"),
           ("Pode representar algo duradouro, primordial e ainda não humanizado, ou uma imagem concentrada da totalidade do self.", "May represent something enduring, primordial and not yet humanized, or a concentrated image of the wholeness of the self.", "Puede representar algo duradero, primordial y aún no humanizado, o una imagen concentrada de la totalidad del sí-mismo."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 232-235",
           "Distinguir pedras comuns, preciosas, trabalhadas e encontradas em lugares sagrados."),
    _entry("circle", ("Círculo", "Circle", "Círculo"),
           ("Pode representar totalidade, centro e organização da vida psíquica, sobretudo quando aparece como uma mandala.", "May represent wholeness, a center and the organization of psychic life, especially when appearing as a mandala.", "Puede representar totalidad, centro y organización de la vida psíquica, especialmente cuando aparece como mandala."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 213-214, 240",
           "Observar divisões em quatro, presença de centro e sensação de equilíbrio ou desordem."),
    _entry("mandala", ("Mandala", "Mandala", "Mandala"),
           ("Imagem de ordenação em torno de um centro; pode indicar movimento de integração, restauração do equilíbrio e relação com o self.", "An image of ordering around a center; it may indicate integration, restored balance and a relationship with the self.", "Imagen de ordenación alrededor de un centro; puede indicar integración, restauración del equilibrio y relación con el sí-mismo."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 213-214",
           "O formato não autoriza sozinho uma conclusão; considerar o afeto e o momento de vida."),
    _entry("shadow", ("Sombra", "Shadow", "Sombra"),
           ("Representa aspectos que o ego não reconhece ou rejeita, incluindo impulsos difíceis e qualidades positivas que não puderam ser vividas.", "Represents aspects the ego does not recognize or rejects, including difficult impulses and positive qualities that could not be lived.", "Representa aspectos que el yo no reconoce o rechaza, incluidos impulsos difíciles y cualidades positivas que no pudieron vivirse."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 61, 116-118",
           "Não reduzir a sombra ao mal: ela também pode conter vitalidade e capacidades criadoras."),
    _entry("hero", ("Herói", "Hero", "Héroe"),
           ("Figura o esforço do ego para adquirir força, reconhecer limites, superar dependências e avançar no desenvolvimento da personalidade.", "Portrays the ego's effort to gain strength, recognize limits, overcome dependencies and advance personality development.", "Representa el esfuerzo del yo por ganar fuerza, reconocer límites, superar dependencias y avanzar en el desarrollo de la personalidad."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 109-116",
           "Vitória, inflação heroica, sacrifício e fracasso correspondem a momentos psíquicos distintos."),
    _entry("child", ("Criança", "Child", "Niño"),
           ("Pode simbolizar vulnerabilidade e origem, mas também potencial novo, desenvolvimento futuro e algo da personalidade que ainda precisa crescer.", "May symbolize vulnerability and origin, but also new potential, future development and something in the personality that still needs to grow.", "Puede simbolizar vulnerabilidad y origen, pero también nuevo potencial, desarrollo futuro y algo de la personalidad que aún necesita crecer."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 69-78, 122",
           "Diferenciar a criança real, a memória biográfica e o motivo arquetípico da criança."),
    _entry("animal", ("Animal", "Animal", "Animal"),
           ("Pode personificar a dimensão instintiva da psique e indicar como o sonhador se relaciona com impulsos naturais ainda pouco integrados.", "May personify the instinctive dimension of the psyche and show how the dreamer relates to natural impulses that are not yet integrated.", "Puede personificar la dimensión instintiva de la psique e indicar cómo el soñante se relaciona con impulsos naturales aún poco integrados."),
           "PSYCHOANALYTIC", "JUNGIAN", JUNG_BOOK, "pp. 94-96, 230-239",
           "A espécie, o comportamento do animal e a relação afetiva do sonhador alteram radicalmente a leitura."),
)
