from dataclasses import dataclass


@dataclass(frozen=True)
class InterpretationKnowledge:
    general: str
    career: str
    consciousness: str
    relationships: str
    source_page: int
    source: str = "Hajo Banzhaf, Guia Completo do Tarô"
    language: str = "en"
    is_paraphrase: bool = True


def K(general, career, consciousness, relationships, source_page):
    return InterpretationKnowledge(
        general=general,
        career=career,
        consciousness=consciousness,
        relationships=relationships,
        source_page=source_page,
    )


# English paraphrases based on the four interpretive blocks used by Banzhaf:
# general meaning, professional life, consciousness, and personal relationships.
# These are NOT quotations. They deliberately preserve the source's domain
# distinctions while remaining compact enough to use as model context.
INTERPRETATION_KNOWLEDGE: dict[str, InterpretationKnowledge] = {
    # MAJOR ARCANA
    "THE_FOOL": K(
        "A fresh encounter with life: spontaneous, open, curious, playful, and free of fixed expectations. It may also show inexperience, naivety, irresponsibility, or a refusal to grow up; the surrounding cards determine which side is dominant.",
        "Entering an unfamiliar professional field with little prior knowledge but strong curiosity and willingness to learn. It can also warn against foolish or irresponsible conduct and against confusing conventional success with genuine fulfillment.",
        "Wonder and openness are the beginning of knowledge. The card can indicate childlike immaturity, but at a deeper level it points toward a simple, unpretentious consciousness reached after experience rather than before it.",
        "A lively, uncomplicated, playful bond in which both people remain open to rediscovering one another. It can also warn of unreliability; at the event level it may mark a stimulating new relationship or a fresh phase in an existing one.",
        19,
    ),
    "THE_MAGICIAN": K(
        "Intelligence, skill, self-awareness, initiative, and the capacity to deal actively with difficult challenges. Its power comes from bringing conscious ability into harmony with deeper, less visible forces.",
        "A phase for taking initiative, using influence deliberately, negotiating, completing difficult projects, and solving problems that have been postponed. Leadership and positive motivation can produce concrete success.",
        "The power of thought and conviction makes previously impossible-seeming conditions attainable. The deeper lesson is to shape one's direction responsibly, consciously, and with determination.",
        "Strong fascination and attraction energize the relationship. Used well, this force can overcome blocks and difficulties, provided influence serves the good of the relationship rather than one person's advantage.",
        21,
    ),
    "THE_HIGH_PRIESTESS": K(
        "Sensitivity, intuition, patience, and deeply rooted trust in forms of knowledge that cannot be reduced to logic. Her bright side is compassionate and healing; her shadow side can use subtle psychic or emotional power to seduce, paralyze, or harm.",
        "Approach work patiently and sincerely, remaining receptive to new impulses and allowing an inner sense of timing to inform decisions. Unconscious or uncontrolled expression of this attitude may appear uncertain, inaccessible, or threatening.",
        "Attention turns toward the unconscious, dreams, images, and hidden layers of the psyche. The card invites discovery of an older, non-dual wisdom that cannot always be divided neatly into good and evil.",
        "Deep understanding, sensitivity, devotion, emotional closeness, and the sense of an invisible bond. When single, it can indicate peaceful solitude and patient openness to future connection without external pressure.",
        23,
    ),
    "THE_EMPRESS": K(
        "The endlessly generative force of nature: vitality, fertility, creativity, growth, change, and the birth of something new. Growth is enriching but may also be unruly and can involve the pain that accompanies genuine creation.",
        "A surge of creative and productive energy brings new ideas, innovation, changing tasks, greater activity, or even a new professional phase. Changes may be disruptive, but the source treats them as fundamentally growth-producing.",
        "New perceptions and understanding reveal the constant flow of life: what passes away makes room for something new. At depth, the card can expose both the nourishing and devouring aspects of the mother archetype.",
        "Growth, renewal, and change within relationships, including family development or a fertile phase in which a new bond can grow. It emphasizes vitality and generally constructive development.",
        25,
    ),
    "THE_EMPEROR": K(
        "Structure, stability, order, discipline, responsibility, sobriety, and pragmatic action. The same impulse can become rigidity, perfectionism, lifelessness, tyranny, or authoritarian control when carried too far.",
        "Organization and realization of long-held plans through clear concepts, discipline, persistence, decision, and willingness to assume responsibility. Success depends strongly on sustained personal effort.",
        "A chaotic idea becomes structured, transparent, realistic, and testable. At a deeper level, the card can stage the tension between the protective father and the distant, demanding authority figure.",
        "A phase of making a relationship stable, reliable, and clearly defined. Its sober search for maximum security can also narrow social life through excessive rigidity or emotional restriction.",
        27,
    ),
    "THE_HIEROPHANT": K(
        "Faith, trust, ethical orientation, and values that give life meaning. It points to moral purpose, confidence in the future, and the search for principles worthy of commitment.",
        "Questions of vocation and meaningful work become more important than security, profit, or recognition alone. The card asks for loyalty to ethical standards and refusal of dubious professional dealings.",
        "A period of examining faith, moral values, and the personal basis of meaning. It sharpens ethical judgment and can correspond to deep religious or spiritual experience.",
        "Mutual trust and affection deepen, while shared values and moral commitments become increasingly important. It may also symbolize the wish or intention to formalize a union through marriage.",
        29,
    ),
    "THE_LOVERS": K(
        "Both love and decision. A profound experience becomes possible only through a wholehearted choice that closes alternative doors; the card can therefore describe romance or any life decision demanding complete commitment.",
        "After weighing the facts, a clear decision should determine future professional behavior. It may concern a new job or field, but can equally mean choosing the present vocation wholeheartedly.",
        "Depth requires commitment rather than endless alternatives. The card exposes the emptiness of remaining permanently undecided and emphasizes the transformative power of a single sincere choice.",
        "A deeply felt love or the discovery of profound happiness in an existing partnership. The decisive theme remains commitment: the relationship grows when one voluntarily chooses this person rather than waiting for an imaginary ideal.",
        31,
    ),
    "THE_CHARIOT": K(
        "A confident leap forward out of familiar territory. Freedom, enterprise, courage, and willingness to take risks are strong, but so are inexperience and the danger of overestimating one's abilities.",
        "A major step toward autonomy, success, increased responsibility, or a new career path. Persistence and boldness help, while unscrupulousness and excessive self-confidence are explicit risks.",
        "A young but powerful consciousness breaks with conventional ideas and develops its own worldview. The task often involves reconciling inner opposites such as feeling and thought, instinct and will, desire and reality.",
        "A new relationship may begin, sometimes together with leaving an older environment behind. In an existing bond, the card brings new wind that can break fatigue, routine, and stale traditions.",
        33,
    ),
    "STRENGTH": K(
        "Vitality, courage, passion, and the reconciliation of civilized consciousness with instinctive nature. Real strength comes not from suppressing instinct but from accepting and gently mastering it.",
        "Wholehearted dedication, physical vitality, courage, initiative, motivation, and strong capacity for achievement. It indicates a phase in which genuine passion for the task can produce success.",
        "Lower or instinctive forces are not condemned but integrated and raised to a higher level. The card describes a profound inner transformation through acceptance rather than repression.",
        "A passionate, vivid, temperamental relationship with strong dramatic energy. Such bonds can become a reservoir of life force, although in extreme cases passion can turn painfully destructive.",
        35,
    ),
    "THE_HERMIT": K(
        "Withdrawal and introspection create the quiet needed to discover who one is, what one wants, and which path is authentic. Chosen solitude can bring clarity, strength, and mature wisdom; unwanted isolation is its difficult side.",
        "A period of professional reflection may radically change previous ideas about prestige, money, success, or vocation. The result can be a quieter but more authentic direction aligned with real needs.",
        "Freedom from other people's opinions allows concentrated self-examination. Silence, meditation, solitude, or disciplined retreat can lead to clarity, courage, and deeper life wisdom.",
        "The card can indicate loneliness even inside a relationship, but its central message is mature understanding of what truly matters. Healthy intimacy may require each partner to retain the capacity to be alone.",
        37,
    ),
    "WHEEL_OF_FORTUNE": K(
        "Events may turn through forces outside immediate control. The same cycle can be experienced as helplessness or as a developmental necessity that teaches timing, humility, growth, and maturity.",
        "Routine or external circumstances may force significant change. If accepted consciously, apparent setbacks can reveal a truer professional path, while favorable phases can bring success, promotion, or advantage.",
        "Life repeatedly confronts us with experiences that must be assimilated in order to grow. The lesson is to understand necessity rather than simply label changing circumstances as good or bad luck.",
        "Relationship circumstances may feel stuck or unsatisfactory, including periods without a partner. The card suggests that something still needs to be learned before the situation can turn toward a more favorable development.",
        39,
    ),
    "JUSTICE": K(
        "Clear judgment, objectivity, honesty, balance, incorruptibility, and responsibility for consequences. The environment reflects one's own conduct: integrity tends to be met by integrity, while dishonest advantage carries a cost.",
        "Seek sober clarity about goals and tasks before deciding how to act. Fair treatment is possible, but deception or unethical business practice undermines the outcome.",
        "A realistic and pragmatic phase in which logical understanding and unbiased judgment matter more than impressions or emotional preference.",
        "Sincerity and balance are central. This can describe harmonious equality or a tense balance of forces; in either case, the relationship reflects back what each person brings into it.",
        41,
    ),
    "THE_HANGED_MAN": K(
        "A forced or chosen suspension in which ordinary progress stops. The situation asks for sacrifice, patience, and a radical reversal of perspective before meaningful release or illumination can occur.",
        "Professional plans may be blocked, delayed, or require giving up a previous approach. Instead of forcing progress, the source emphasizes examining the deeper reason for the standstill and changing perspective.",
        "A profound inner reversal can transform how the situation is understood. What first appears to be paralysis may become an initiation into a different level of insight.",
        "A relationship may enter a stagnant, suspended, or sacrificial phase. The card asks whether old expectations must be relinquished before the bond can be seen and lived differently.",
        43,
    ),
    "DEATH": K(
        "A real ending, farewell, and release. Something has completed its cycle and must be consciously let go so that the new can eventually emerge; the emphasis is transformation through ending rather than literal death.",
        "A professional phase, task, role, or direction has reached its natural conclusion. The necessary work is to complete, release, and clear space rather than artificially prolong what is finished.",
        "Consciousness confronts impermanence and the necessity of letting go. Acceptance of endings becomes a condition for psychological renewal and deeper development.",
        "An old form of relating reaches an end. This can indicate separation, but may also mean that a previous pattern within the relationship must die so that a fundamentally different one can emerge.",
        45,
    ),
    "TEMPERANCE": K(
        "Harmony, moderation, balance, health, patience, and the peaceful integration of opposing forces. It represents the right measure rather than dramatic extremes.",
        "A calm, balanced approach favors cooperation and sustainable development. Progress comes through moderation, good timing, and combining different factors rather than forcing one-sided solutions.",
        "Inner opposites are reconciled into a more harmonious whole. The card encourages emotional and psychological equilibrium and a patient process of healing.",
        "A peaceful, harmonious, and mutually strengthening relationship atmosphere. It favors reconciliation, patience, and a balanced exchange in which neither side must overpower the other.",
        47,
    ),
    "THE_DEVIL": K(
        "Bondage to shadow forces, compulsions, dependency, temptation, or disowned parts of the personality. The card's task is recognition: what remains unintegrated gains power precisely because it is denied.",
        "Work may be shaped by dependency, unethical entanglement, manipulation, material obsession, or an environment that binds through fear and desire. Recognizing the chain is the first step toward freedom.",
        "The card confronts the shadow: drives, fears, desires, and projections the conscious personality would rather disown. Integration requires seeing these forces without moralistic denial.",
        "Strong attraction can become dependency, jealousy, manipulation, sexual compulsion, or an unhealthy bond. The card does not simply condemn desire; it asks where desire has become a chain.",
        49,
    ),
    "THE_TOWER": K(
        "A sudden breakthrough destroys structures that have become rigid, false, or too narrow. The disruption is frightening but can release vitality and freedom that were trapped inside the old form.",
        "A professional structure, plan, role, or assumption may break down abruptly. Rather than restoring the old form at any cost, the event can reveal where a more truthful and viable structure is needed.",
        "A fixed worldview or self-image is shattered by a realization that can no longer be contained. The crisis becomes liberating when the new truth is allowed to reorganize consciousness.",
        "Established relationship structures may crack, exposing tensions that could no longer remain hidden. This may be disruptive, yet it can also free the bond from false expectations and stale forms.",
        51,
    ),
    "THE_STAR": K(
        "Hope, confidence, clarity, and long-range vision. After difficulty, the situation can be viewed from a wider perspective and planned with trust in future development.",
        "Good prospects become visible when planning extends beyond the immediate moment. The card supports long-term goals, confidence, and work whose development requires a broad horizon.",
        "A wider understanding restores trust and orientation. The mind can connect present experience with a meaningful future instead of remaining trapped in immediate anxiety.",
        "The relationship gains hope, openness, and a sense of future possibility. It favors trust and a wider perspective on how the bond can develop over time.",
        53,
    ),
    "THE_MOON": K(
        "A descent into uncertainty, fear, dream, and the hidden depths of the psyche. The path cannot be navigated by ordinary certainty alone, and courage is needed to distinguish intuition from projection and anxiety.",
        "Professional circumstances may be unclear, emotionally charged, or difficult to evaluate. The source theme favors proceeding carefully through uncertainty rather than pretending that the path is already fully visible.",
        "Consciousness enters the underworld of fears, fantasies, and unconscious material. The developmental task is to face what is hidden without becoming lost in illusion.",
        "Uncertainty, projection, fear, or emotional ambiguity may color the relationship. The card asks for honesty about insecurity and for patience before turning subjective impressions into facts about the other person.",
        55,
    ),
    "THE_SUN": K(
        "Joy of life, vitality, creativity, openness, warmth, and generous self-expression. It is one of the clearest images of confidence, illumination, and uncomplicated affirmation of life.",
        "Work can become joyful, successful, creative, and openly rewarding. Confidence and a positive atmosphere favor recognition, cooperation, and the free use of one's abilities.",
        "Clarity and a generous consciousness replace obscurity. The card points toward self-acceptance, vitality, and the ability to experience life without unnecessary inner division.",
        "Warmth, affection, deep understanding, sincere acceptance, and generous love characterize the bond. It is strongly favorable for happiness and open-hearted partnership.",
        57,
    ),
    "JUDGEMENT": K(
        "Liberation, redemption, awakening, and the recovery of something that had been buried or imprisoned. A decisive call brings the possibility of renewal on a deeper level.",
        "A professional calling, dormant possibility, or previously blocked path may be released. The card can indicate a decisive turning point in which work becomes aligned with a deeper sense of purpose.",
        "A buried part of the self is recognized and reintegrated. Consciousness awakens to a decisive truth that frees it from an older condition.",
        "A relationship can undergo a profound renewal, reconciliation, or liberating realization. The decisive issue is whether both people can respond to what has now become impossible to ignore.",
        59,
    ),
    "THE_WORLD": K(
        "Completion, wholeness, harmony, fulfillment, and the experience of having arrived where one belongs. It often marks an important completed stage rather than an absolute end to all development.",
        "A strong confirmation that one is in the right profession, workplace, or direction. It favors success, harmony with others, and sometimes international contacts or travel.",
        "A decisive step toward authenticity and inner totality has been achieved. Former contradictions can now be seen as parts of a larger, coherent whole.",
        "A deep sense of being at home in the relationship. It can indicate a lasting partnership, marriage, or meeting a life companion rather than a merely temporary connection.",
        61,
    ),

    # WANDS
    "ACE_OF_WANDS": K(
        "An inner opportunity for courage, determination, enthusiasm, risk-taking, willpower, and self-development. It is strongly life-affirming and can also contain impatience.",
        "A chance to recognize goals, develop talents, take risks, and commit energetically to work. It can indicate major possibilities for professional realization and strong motivation.",
        "Will, conviction, moral strength, self-confidence, and inner growth become stronger.",
        "Warmth, vitality, honesty, and enthusiasm increase within a relationship. It may signal a promising new bond or renewed passion in an existing one, though tempers can also flare.",
        63,
    ),
    "TWO_OF_WANDS": K(
        "A warning against neutrality, indifference, and theoretical intention without real commitment. The way out is to turn ideas into conviction and intention into action.",
        "Work is being performed without inner participation, or important disputes are met with pale neutrality. The card calls for a clear personal position and genuine engagement.",
        "A lethargic phase in which words and opinions lack real conviction. Progress begins when a definite inner commitment is formed.",
        "Lukewarm feeling and emotional withdrawal can gradually cool a relationship. A clear decision is required: either separate or genuinely come to terms with the partnership.",
        65,
    ),
    "THREE_OF_WANDS": K(
        "A stable foundation, confidence, and a broad view of what lies ahead. It indicates that one can look toward future development from a reliable base.",
        "Plans rest on solid ground and can be expanded with confidence. Long-range thinking, reliability, and a clear view of future possibilities are favored.",
        "Confidence grows from understanding that a secure basis has already been established. This supports a more expansive and future-oriented outlook.",
        "The relationship stands on a reliable foundation and can be viewed with confidence. It favors trust in shared development and future possibilities.",
        67,
    ),
    "FOUR_OF_WANDS": K(
        "Joy, openness, peace, sociability, celebration, and the willingness to step out into life. It favors friendly encounters and a protected, enjoyable atmosphere.",
        "A pleasant and cooperative professional climate, successful completion of a stage, or a reason to celebrate progress with others.",
        "The mind opens outward with relief and confidence rather than remaining defensive. Enjoyment and sociability are part of the lesson.",
        "A joyful, friendly, open phase that encourages meeting people, celebrating, and sharing affection. It supports harmony and a sense of welcome.",
        69,
    ),
    "FIVE_OF_WANDS": K(
        "A challenge, contest, or test of strength that should be approached as a stimulating game rather than a destructive war.",
        "Competition or a demanding task provides the chance to measure abilities and improve through effort. The emphasis is on healthy contest rather than hostility.",
        "The card stimulates courage to test oneself and discover capabilities through challenge.",
        "Differences can create lively friction, but the conflict need not be destructive. It may energize the relationship when both sides can compete without trying to humiliate one another.",
        71,
    ),
    "SIX_OF_WANDS": K(
        "Success, victory, recognition, and encouraging news. Confidence is justified because effort is becoming visible and acknowledged.",
        "Professional success, praise, promotion, recognition, or the successful completion of a challenge is strongly favored.",
        "Self-confidence is strengthened by the realization that one has successfully overcome an important difficulty.",
        "A favorable development brings encouragement, recognition, and renewed confidence within the bond. It can also indicate welcome news concerning the relationship.",
        73,
    ),
    "SEVEN_OF_WANDS": K(
        "A position of advantage is under pressure and must be defended. Skill, alertness, courage, and firm boundaries are needed.",
        "Competition, criticism, or opposition threatens what has been achieved, but the card suggests that the position is stronger than it may initially seem.",
        "The task is to recognize one's real advantage and resist being psychologically pushed out of a position by fear.",
        "Outside pressure or conflict may challenge the relationship. The card favors defending what matters while avoiding unnecessary paranoia or aggression.",
        75,
    ),
    "EIGHT_OF_WANDS": K(
        "Movement accelerates and events approach quickly. Timing, messages, developments, and the sense that something is already in motion are central.",
        "Projects or negotiations may advance rapidly, and important news can arrive soon. Responsiveness and good timing matter more than prolonged hesitation.",
        "The mind should recognize that a process has already begun and that the present moment calls for attention to timing and unfolding signals.",
        "Contacts, messages, meetings, or emotional developments can happen quickly. A stagnant relationship may suddenly become active.",
        77,
    ),
    "NINE_OF_WANDS": K(
        "A defensive posture shaped by previous difficulty. Persistence is necessary, but the card warns against turning justified caution into permanent suspicion.",
        "Past problems may make one guarded at work. The card favors protecting gains and persevering without retreating simply because another difficulty appears.",
        "An old wound or expectation of attack still shapes perception. Consciousness must distinguish realistic caution from fear-based defensiveness.",
        "Previous hurt can make intimacy difficult and produce guarded behavior. The card asks for resilience without building a wall so strong that connection becomes impossible.",
        79,
    ),
    "TEN_OF_WANDS": K(
        "Heavy burden, pressure, oppression, and a narrowed sense of perspective. Responsibilities or expectations have accumulated beyond a comfortable level.",
        "Workload, responsibility, or ambition has become exhausting. The card can indicate carrying too much alone and losing sight of the broader purpose.",
        "Mental pressure makes the future appear more limited than it really is. The lesson is to recognize how burden and fear distort perspective.",
        "The relationship may feel weighed down by duties, expectations, or emotional pressure. Relief requires acknowledging what has become too heavy to carry in the same way.",
        81,
    ),
    "PAGE_OF_WANDS": K(
        "An external opportunity, invitation, or impulse toward adventure arrives. It is a chance that asks for enthusiasm and courage.",
        "A promising offer, project, invitation, or professional opening may appear from outside. It deserves an energetic response rather than timid refusal.",
        "A new possibility awakens enthusiasm and the desire to explore unfamiliar experience.",
        "A lively invitation, flirtation, or new impulse can enter the relationship sphere. It brings excitement but still needs development before its long-term meaning is clear.",
        83,
    ),
    "KNIGHT_OF_WANDS": K(
        "A fiery state of mind full of initiative, movement, adventure, impatience, and appetite for action.",
        "Strong drive favors bold professional movement and entrepreneurial action, but impatience can make one rush beyond what the situation can sustain.",
        "The psyche is restless, adventurous, and eager for immediate experience. The task is to use energy without allowing it to become uncontrolled impulsiveness.",
        "Passion, excitement, travel, or sudden movement can energize a bond, but reliability may suffer if the desire for intensity is stronger than the willingness to remain.",
        85,
    ),
    "QUEEN_OF_WANDS": K(
        "A warm, self-confident, independent, proud, and life-loving expression of Fire. It combines vitality with strong personal presence.",
        "Confidence, initiative, creativity, and the ability to motivate others support professional progress. The shadow is excessive pride or domination.",
        "The card encourages trust in one's vitality, dignity, and independent inner fire.",
        "Warmth, passion, loyalty, and spirited affection can strengthen a relationship. Strong temperament should not turn into jealousy or domination.",
        87,
    ),
    "KING_OF_WANDS": K(
        "Sovereignty, confidence, generosity, conviction, and mature command of the Fire principle.",
        "Leadership, entrepreneurial vision, confidence, and the ability to inspire others are emphasized. Success depends on using authority generously rather than autocratically.",
        "A clear inner conviction gives direction and the courage to assume responsibility for one's path.",
        "A strong, warm, confident presence can stabilize and energize the bond. The challenge is to lead without controlling the other person.",
        89,
    ),

    # SWORDS
    "ACE_OF_SWORDS": K(
        "An inner opportunity for clarity, discernment, decisive understanding, and the power to cut through confusion.",
        "A clear analysis, sharp decision, or intellectual breakthrough can solve a professional problem. Objectivity and precise reasoning are favored.",
        "The mind gains the ability to distinguish, understand, and synthesize what previously seemed entangled.",
        "Clarity and honest conversation can cut through ambiguity in a relationship. The sword should be used to understand, not simply to wound.",
        91,
    ),
    "TWO_OF_SWORDS": K(
        "Deep inner doubt creates a stalemate. Skepticism may be useful, but indefinite suspension prevents real engagement with the problem.",
        "Uncertainty or conflicting information makes professional decisions difficult. The card advises critical examination before commitment.",
        "A divided mind protects itself from decision by holding opposing possibilities in suspension.",
        "Emotional uncertainty and guarded communication can create distance. The issue cannot be resolved merely by avoiding a difficult conversation.",
        93,
    ),
    "THREE_OF_SWORDS": K(
        "A painful truth, separation, or decision made against feeling. Clarity is achieved, but not without emotional cost.",
        "A difficult professional decision may require giving up something valued or accepting an unpleasant fact.",
        "The intellect cuts through an attachment or illusion that feeling would prefer to preserve. The lesson is painful honesty rather than needless cruelty.",
        "Heartbreak, disappointment, painful honesty, or separation may be present. The card asks that the pain be acknowledged directly instead of disguised.",
        95,
    ),
    "FOUR_OF_SWORDS": K(
        "A period of inactivity, blockage, recovery, or enforced rest. Action cannot simply continue at the previous pace.",
        "Projects may pause or creativity may be blocked. Rest, recovery, or temporary withdrawal can be more productive than forcing activity.",
        "The mind needs distance and quiet before it can become active again.",
        "Emotional exchange may temporarily slow or stop. The bond can need space and recovery rather than immediate pressure for resolution.",
        97,
    ),
    "FIVE_OF_SWORDS": K(
        "Destructive conflict, defeat, humiliation, betrayal, or a victory purchased at an excessive cost.",
        "A professional dispute may become hostile or unethical. Winning by destructive means can damage the larger situation more than losing gracefully.",
        "The card exposes the mentality of conflict in which proving superiority becomes more important than truth or constructive resolution.",
        "Quarrels can become cruel, humiliating, or vindictive. The priority is to stop escalation and recognize when 'winning' would destroy the relationship itself.",
        99,
    ),
    "SIX_OF_SWORDS": K(
        "A transition away from familiar surroundings toward an uncertain but potentially necessary new horizon.",
        "A job change, relocation, new field, or departure from familiar professional conditions may be indicated. The new territory is not fully known yet.",
        "Consciousness leaves an old mental environment and begins learning a different way of seeing.",
        "The relationship may be moving through a transition, departure, or change of emotional environment. What comes next is not yet completely visible.",
        101,
    ),
    "SEVEN_OF_SWORDS": K(
        "Cunning, evasion, trickery, concealment, or strategic intelligence. The source emphasizes the danger that cleverness becomes dishonesty.",
        "Professional strategy may involve indirect methods, but deception, theft, or manipulation can undermine trust and create future problems.",
        "The mind may be rationalizing or using cleverness to avoid a more honest confrontation with reality.",
        "Hidden motives, avoidance, or dishonesty can weaken trust. The card favors checking assumptions and behavior rather than immediately accusing the other person.",
        103,
    ),
    "EIGHT_OF_SWORDS": K(
        "Restriction and inhibition, often maintained by internal prohibitions that are experienced as if they were purely external limits.",
        "Fear, lack of confidence, or restrictive circumstances can make professional options seem narrower than they are. Some limitation is real, but some may be self-maintained.",
        "Consciousness is trapped by its own assumptions, anxieties, or prohibitions. Freedom begins by identifying which boundaries actually come from within.",
        "Fear of rejection, vulnerability, or conflict can inhibit honest expression. The bond may feel trapped because neither side sees how internal fears shape the apparent limits.",
        105,
    ),
    "NINE_OF_SWORDS": K(
        "Worry, guilt, remorse, fear, and oppressive thoughts that become especially powerful when carried alone.",
        "Professional anxiety may be magnified by fear of failure, guilt, or anticipation of consequences. The card encourages bringing the problem into the open rather than suffering silently.",
        "The mind is caught in painful repetitive thought. Naming fear and responsibility clearly is more useful than self-punishment.",
        "Anxiety, guilt, or fear of loss can dominate the relationship experience. Honest communication about fears is preferable to silently imagining the worst.",
        107,
    ),
    "TEN_OF_SWORDS": K(
        "A harsh but definitive ending. A situation has reached a boundary beyond which its old form cannot continue.",
        "A project, position, or professional phase may be terminated abruptly or deliberately. Once ended, it creates space for a radically different beginning.",
        "The mind must accept finality instead of repeatedly trying to revive what has already concluded.",
        "A painful relationship pattern may reach its end, and in some cases the bond itself may end. The card emphasizes finality rather than endless continuation of the same wound.",
        109,
    ),
    "PAGE_OF_SWORDS": K(
        "An external challenge, criticism, provocation, or message that tests alertness and intellectual discrimination.",
        "Criticism, difficult news, disagreement, or a challenging conversation may arise. It should be met with clarity rather than reactive hostility.",
        "The card sharpens critical awareness and asks whether a challenge contains useful information beneath its irritating form.",
        "A provocative message, suspicion, criticism, or argument may enter the relationship. The task is to investigate clearly instead of letting conflict feed on gossip or assumption.",
        111,
    ),
    "KNIGHT_OF_SWORDS": K(
        "A cold, severe, confrontational mental atmosphere. Reason is fast and sharp, but can become merciless.",
        "A situation may require rapid, uncompromising analysis or confrontation. The danger is turning intellectual rigor into aggression or destructive conflict.",
        "The mind cuts quickly and decisively, but must distinguish disciplined clarity from hostility.",
        "Emotional warmth may be replaced by distance, criticism, or confrontation. Difficult issues can be addressed, but cruelty and verbal violence worsen them.",
        113,
    ),
    "QUEEN_OF_SWORDS": K(
        "Independent, discerning, individualistic, and intellectually clear expression of Air.",
        "Professional independence, objectivity, experience, and clear judgment are assets, especially where difficult decisions require emotional distance.",
        "The card favors intellectual autonomy and a perspective not governed by social pressure.",
        "Honesty and independence matter strongly in the bond. Healthy distance can clarify the relationship, while excessive coldness can turn autonomy into isolation.",
        115,
    ),
    "KING_OF_SWORDS": K(
        "Intellectual command, versatility, wit, strategy, and sharp reasoning. Its shadow is cleverness used manipulatively.",
        "Strategic thinking, expertise, analysis, communication, and rational authority support professional leadership.",
        "The mind seeks mastery through knowledge, argument, and conceptual clarity. The challenge is to use intelligence in service of truth rather than superiority.",
        "Clear communication and rational perspective can help, but the bond suffers if emotional reality is dismissed in favor of intellectual control.",
        117,
    ),

    # PENTACLES
    "ACE_OF_PENTACLES": K(
        "An inner opportunity for tangible value, security, prosperity, and fulfillment that can be made real through practical engagement.",
        "A promising material or professional opportunity can become stable growth if recognized and cultivated carefully.",
        "The card invites recognition of what is genuinely valuable and capable of giving durable form to intention.",
        "A relationship can gain stability, trust, sensual warmth, and practical grounding. It can also signal a valuable new opportunity for connection.",
        119,
    ),
    "TWO_OF_PENTACLES": K(
        "Adaptability, flexibility, playfulness, and the ability to move with changing circumstances, though the same fluidity can become inconsistency.",
        "Several demands may need to be balanced at once. Lightness and adaptability help, but unreliable priorities can undermine progress.",
        "The card encourages flexible thinking and warns against treating everything with either excessive seriousness or careless indifference.",
        "The relationship may be in a playful, changeable phase. Flexibility helps, while inconsistency can make the other person unsure of where they stand.",
        121,
    ),
    "THREE_OF_PENTACLES": K(
        "Competence, learning, achievement, qualification, and entry into a more advanced stage of development.",
        "Skill is recognized and a new professional level can be reached through disciplined learning, collaboration, and demonstrated ability.",
        "Growth requires acknowledging that mastery is never complete and remaining willing to learn.",
        "The bond can mature through practical effort and learning how to build something together rather than relying only on feeling.",
        123,
    ),
    "FOUR_OF_PENTACLES": K(
        "The desire for security, possession, preservation, and control. What begins as stability can become obsessive attachment or fear of loss.",
        "Resources, position, or status may be guarded carefully. Excessive security-seeking can block opportunity and make work rigid.",
        "Consciousness is preoccupied with keeping what it has. The deeper question is whether security is serving life or replacing it.",
        "Possessiveness, fear of loss, or the need to control the bond can restrict affection. Reliable commitment is valuable, but emotional hoarding is not.",
        125,
    ),
    "FIVE_OF_PENTACLES": K(
        "Crisis, scarcity, hardship, insecurity, or exclusion. The card also emphasizes that help may exist if pride and isolation are overcome.",
        "Financial or professional obstacles create a difficult period. Practical support and willingness to ask for assistance are important.",
        "A scarcity mentality can intensify suffering by making the person feel alone and without options.",
        "A relationship may pass through hardship, loneliness, or insecurity. Mutual support matters, and withdrawing in shame can deepen the difficulty.",
        127,
    ),
    "SIX_OF_PENTACLES": K(
        "Generosity, assistance, tolerance, giving, and receiving. Resources flow constructively when help is offered without humiliating the receiver.",
        "Material support, fair compensation, assistance, sponsorship, or useful cooperation may be available. The ethics of power in giving and receiving matter.",
        "The card asks for a mature relationship to resources: being able both to help and to accept help.",
        "Mutual support and generosity strengthen the bond. Imbalance appears when one person controls the other through what is given or withheld.",
        129,
    ),
    "SEVEN_OF_PENTACLES": K(
        "Slow but reliable growth. Patience is required because a living process cannot be accelerated indefinitely without harming it.",
        "Results develop gradually through sustained effort. The card favors cultivation and long-term patience over abandoning the project too early.",
        "The lesson is trust in gradual development and the ability to wait without confusing patience with passivity.",
        "The relationship needs time to develop organically. Pressure for immediate certainty may damage something that is actually growing in a healthy but slow way.",
        131,
    ),
    "EIGHT_OF_PENTACLES": K(
        "Learning, skill, practice, craftsmanship, and disciplined improvement.",
        "Professional progress comes through training, repetition, attention to detail, and willingness to remain an apprentice where necessary.",
        "The mind grows through practice rather than abstract intention alone. Humility toward learning is central.",
        "The relationship improves through concrete effort, learning from mistakes, and repeatedly practicing healthier ways of relating.",
        133,
    ),
    "NINE_OF_PENTACLES": K(
        "Gain, enjoyment, reward, confidence, and the ability to appreciate what has been successfully cultivated.",
        "A favorable professional or financial phase can bring profit, recognition, and the enjoyment of results.",
        "The card supports confidence grounded in demonstrated competence and the capacity to enjoy achievement without guilt.",
        "A comfortable and pleasurable phase can strengthen the bond, especially when each person can enjoy both closeness and personal self-sufficiency.",
        135,
    ),
    "TEN_OF_PENTACLES": K(
        "Abundance, stable structures, long-term security, inheritance, and continuity.",
        "Established prosperity, durable business structures, family assets, or long-term material security are emphasized.",
        "The card expands the idea of value beyond immediate gain toward continuity, tradition, and what can endure beyond the present moment.",
        "A stable, long-lasting bond with strong family or community roots is favored. Shared material and practical structures can become part of the relationship's strength.",
        137,
    ),
    "PAGE_OF_PENTACLES": K(
        "A valuable external opportunity arrives in practical form. It may appear modest but contains real potential if taken seriously.",
        "An offer, training opportunity, practical project, or material chance deserves careful attention and realistic follow-through.",
        "The card invites curiosity about a concrete possibility and willingness to learn how to turn it into something useful.",
        "A sincere and practical offer can strengthen the relationship or open the way to a new bond. Small gestures may carry greater value than dramatic promises.",
        139,
    ),
    "KNIGHT_OF_PENTACLES": K(
        "Reliability, patience, steadiness, solid values, and disciplined persistence.",
        "Slow, careful, methodical work is favored. Durable results come from consistency rather than dramatic leaps.",
        "The card supports commitment to stable values and the patience to let results develop through repetition and responsibility.",
        "Loyalty, reliability, and practical commitment create security. The shadow is stagnation when stability becomes resistance to all change.",
        141,
    ),
    "QUEEN_OF_PENTACLES": K(
        "Grounded, fertile, caring, practical, and family-oriented expression of Earth.",
        "Practical intelligence, patience, care for resources, and realistic judgment support stable professional development.",
        "The card encourages embodied common sense: knowing through practical contact with reality rather than abstraction alone.",
        "Warmth is expressed through care, reliability, sensuality, and practical support. The relationship benefits from a secure and nurturing environment.",
        143,
    ),
    "KING_OF_PENTACLES": K(
        "Mature command of material reality, stable values, sensual enjoyment, stewardship, and practical authority.",
        "Business competence, resource management, reliability, and realistic leadership can produce durable prosperity.",
        "The card asks for a mature understanding of material value: possession should serve life rather than become its only measure.",
        "Security, loyalty, sensuality, and practical reliability can anchor the bond. Excessive possessiveness or material fixation is the main risk.",
        145,
    ),

    # CUPS
    "ACE_OF_CUPS": K(
        "An inner opening toward deep fulfillment, love, emotional renewal, blessing, and the capacity to receive what genuinely nourishes the heart.",
        "Work can become emotionally fulfilling or bring a new opportunity that feels deeply meaningful rather than merely advantageous.",
        "The card opens consciousness toward receptivity, gratitude, compassion, and a fuller experience of feeling.",
        "A strong sign of love, reconciliation, tenderness, and emotional fulfillment. It may signal a new relationship or a deep renewal of feeling in an existing one.",
        147,
    ),
    "TWO_OF_CUPS": K(
        "Meeting, reciprocity, affection, reconciliation, and the formation of a mutually welcoming bond.",
        "Partnership, agreement, constructive cooperation, or a helpful alliance may form through genuine reciprocity.",
        "The card emphasizes the ability to meet another person or perspective without domination, creating a balanced exchange.",
        "A direct image of mutual affection, attraction, reconciliation, and partnership. Its central quality is reciprocity rather than one-sided longing.",
        149,
    ),
    "THREE_OF_CUPS": K(
        "Joy, gratitude, celebration, friendship, and shared emotional abundance.",
        "A successful stage can be celebrated with colleagues or collaborators. Cooperative atmosphere and social support are favorable.",
        "Gratitude and enjoyment help consciousness recognize that fulfillment can be shared rather than privately possessed.",
        "Friendship, celebration, affection, and social joy strengthen the emotional field. It favors happy gatherings and supportive companionship.",
        151,
    ),
    "FOUR_OF_CUPS": K(
        "Discontent, irritation, boredom, or emotional withdrawal make it difficult to appreciate what is being offered.",
        "Dissatisfaction with routine or current conditions can reduce motivation. Before rejecting an opportunity, examine whether frustration is distorting perception.",
        "The psyche closes itself off through irritation or apathy. The task is to understand the source of dissatisfaction rather than feed it indefinitely.",
        "One person may withdraw, become moody, or fail to notice genuine affection because attention is fixed on disappointment.",
        153,
    ),
    "FIVE_OF_CUPS": K(
        "Grief, loss, bitterness, disappointment, and the need to accept consolation rather than remain isolated in sorrow.",
        "A setback or loss may need to be mourned before practical movement resumes. Support should be accepted instead of treating the loss as solitary failure.",
        "Consciousness is occupied by what has been lost. Healing begins when grief is acknowledged without allowing it to define the whole field of experience.",
        "Sadness, disappointment, or separation affects the bond. The card emphasizes mourning honestly and remaining open to comfort and surviving connection.",
        155,
    ),
    "SIX_OF_CUPS": K(
        "Memory, nostalgia, tenderness, and emotionally charged recollection of the past.",
        "Past experience, former contacts, or earlier skills may become relevant again. Nostalgia should not replace realistic evaluation of present conditions.",
        "Memory shapes present perception, sometimes beautifully and sometimes through idealization.",
        "Old feelings, former partners, shared memories, or a romanticized past may become important. Tenderness is genuine, but the past should not be confused with the present.",
        157,
    ),
    "SEVEN_OF_CUPS": K(
        "Fantasy, illusion, temptation, and seductive possibilities that may not correspond to reality.",
        "Too many attractive possibilities, unrealistic promises, or wishful thinking can make professional judgment unreliable. Clarification is needed before commitment.",
        "The mind projects desires into images and then risks mistaking those images for reality. Disillusionment can therefore be constructive.",
        "Idealization, fantasy, mixed signals, or unrealistic expectations may cloud the bond. The card warns against loving an imagined person more than the actual one.",
        159,
    ),
    "EIGHT_OF_CUPS": K(
        "A sorrowful departure from something emotionally important that can no longer be continued in the same way.",
        "Leaving a familiar professional situation may be painful but necessary. The new direction is not yet fully formed.",
        "Consciousness accepts that emotional attachment alone is not sufficient reason to remain in a completed situation.",
        "A painful farewell, emotional withdrawal, or necessary departure may occur. The card does not imply lack of feeling; often the difficulty lies precisely in leaving something that still matters.",
        161,
    ),
    "NINE_OF_CUPS": K(
        "Pleasure, sociability, enjoyment, satisfaction, hospitality, and the ability to appreciate a favorable phase.",
        "Work or material conditions may become comfortable and rewarding enough to be genuinely enjoyed.",
        "The card encourages conscious enjoyment and gratitude instead of postponing happiness indefinitely.",
        "A pleasurable, affectionate, sociable phase favors shared meals, gifts, celebration, and emotional ease.",
        163,
    ),
    "TEN_OF_CUPS": K(
        "Emotional harmony, protection, happy closeness, belonging, and a supportive communal or family atmosphere.",
        "A cooperative and emotionally positive environment supports work, especially where trust and shared purpose matter.",
        "The card represents an experience of emotional wholeness in which personal feeling is integrated with belonging to others.",
        "One of the clearest images of shared happiness, family harmony, emotional security, and mutual gratitude.",
        165,
    ),
    "PAGE_OF_CUPS": K(
        "A kind gesture, invitation, reconciliation, affectionate message, or emotionally promising opportunity comes from outside.",
        "A friendly offer, invitation, or cooperative gesture may improve professional relationships and open a useful opportunity.",
        "The psyche becomes receptive to kindness, play, reconciliation, and the possibility that a small emotional signal can matter.",
        "Flirtation, apology, invitation, affectionate communication, or reconciliation may enter the situation. It is promising, though still young and developing.",
        167,
    ),
    "KNIGHT_OF_CUPS": K(
        "A gentle, romantic, conciliatory, dreamy, and emotionally receptive atmosphere.",
        "Diplomacy, tact, creativity, aesthetics, or a conciliatory approach may work better than force. The mood favors cooperation but can become overly idealistic.",
        "Feeling, imagination, beauty, and intuition temporarily take priority over hard-edged analysis.",
        "Romance, tenderness, reconciliation, affection, and idealistic feeling are emphasized. The challenge is to enjoy the emotional current without confusing fantasy with durable commitment.",
        169,
    ),
    "QUEEN_OF_CUPS": K(
        "Sensitive, intuitive, empathic, receptive, and caring expression of Water.",
        "Empathy, counseling ability, intuition, and sensitivity to other people's needs can be valuable professional strengths.",
        "The card deepens contact with intuition and subtle emotional perception, while requiring boundaries so sensitivity does not become overwhelm.",
        "Deep empathy, tenderness, emotional understanding, and intuitive closeness support the bond. Excessive absorption in the other person's moods is the main risk.",
        171,
    ),
    "KING_OF_CUPS": K(
        "Mature emotional wisdom, instinctive understanding, compassion, support, and active command of the Water principle.",
        "Diplomacy, emotional intelligence, counseling, mediation, and compassionate leadership are favored.",
        "Feeling is not rejected but understood and held with maturity. The card points toward wisdom that integrates emotion without being ruled by it.",
        "A mature, compassionate, supportive emotional presence can stabilize the relationship. The strongest expression is care with self-command rather than emotional suppression.",
        173,
    ),
}
