from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class CardMetadata:
    upright_keywords: tuple[str, ...]
    upright_meaning: str
    reversed_keywords: tuple[str, ...]
    reversed_meaning: str
    element: Optional[str]
    astrological_association: str
    source_page: int
    reversed_is_derived: bool = True


# Source basis:
# Hajo Banzhaf, Guia Completo do Tarô.
#
# The source explicitly supplies the card interpretations and astrological
# equivalents, and explicitly maps the Minor Arcana suits to elements:
# Wands=Fire, Swords=Air, Pentacles=Earth, Cups=Water.
#
# Banzhaf does not use reversed-card meanings in this book. Therefore the
# reversed fields below are intentionally DERIVED from the source's own
# negative, blocked, excessive, immature, or shadow expressions of each card.
# They are not presented as quotations or as an explicit reversed-card system
# authored by Banzhaf.
#
# For Major Arcana, element is None because this source does not provide a
# systematic elemental correspondence for each Major Arcana card.


CARD_METADATA: dict[str, CardMetadata] = {
    # -------------------------
    # MAJOR ARCANA
    # -------------------------
    "THE_FOOL": CardMetadata(
        ("new beginning", "openness", "spontaneity", "curiosity", "freedom"),
        "A spontaneous entry into new experience with openness, honesty, curiosity, and freedom from fixed expectations.",
        ("recklessness", "naivety", "irresponsibility", "aimlessness", "immaturity"),
        "The impulse toward the new becomes careless, ungrounded, avoidant of responsibility, or unable to learn from experience.",
        None,
        "Uranus/Mercury as receptivity, curiosity, spontaneity and folly; with Neptune as the experience of being led.",
        19,
    ),
    "THE_MAGICIAN": CardMetadata(
        ("initiative", "skill", "will", "self-confidence", "mastery"),
        "Conscious power, intelligence, dexterity, and initiative are available to shape circumstances and meet challenges effectively.",
        ("manipulation", "overconfidence", "misused power", "demagoguery", "blocked initiative"),
        "Ability and influence are distorted by excessive force, manipulation, showmanship, or failure to act with clear purpose.",
        None,
        "Sun as power and radiance; Mercury as skill and dexterity.",
        21,
    ),
    "THE_HIGH_PRIESTESS": CardMetadata(
        ("intuition", "patience", "receptivity", "inner knowing", "mystery"),
        "Trust in intuition, patience, sensitivity, and the quiet knowledge that emerges beyond purely rational understanding.",
        ("passivity", "confusion", "secretiveness", "emotional manipulation", "blocked intuition"),
        "Receptivity turns into paralysis, obscure motives, unhealthy secrecy, or mistrust of one's own inner perception.",
        None,
        "Moon as lunar consciousness, understanding, and the power of unknown inner forces.",
        23,
    ),
    "THE_EMPRESS": CardMetadata(
        ("fertility", "growth", "creativity", "abundance", "renewal"),
        "Creative life force brings growth, fertility, new ideas, change, and the capacity to give emerging possibilities form.",
        ("overgrowth", "excess", "stagnant creativity", "smothering", "disorder"),
        "Growth becomes uncontrolled or blocked, producing excess, dispersion, dependency, or creative energy without useful form.",
        None,
        "Venus in Taurus as fertility and growth.",
        25,
    ),
    "THE_EMPEROR": CardMetadata(
        ("structure", "responsibility", "order", "stability", "realism"),
        "The need to establish order, responsibility, structure, continuity, and a reliable foundation through disciplined action.",
        ("rigidity", "authoritarianism", "control", "stubbornness", "fear of change"),
        "Healthy structure hardens into domination, inflexibility, excessive control, or an inability to adapt.",
        None,
        "Sun in Capricorn as responsibility, order, certainty, structure, continuity, and perseverance.",
        27,
    ),
    "THE_HIEROPHANT": CardMetadata(
        ("meaning", "faith", "tradition", "guidance", "values"),
        "A search for meaning, trustworthy principles, spiritual or ethical orientation, and guidance rooted in enduring values.",
        ("dogmatism", "empty convention", "blind obedience", "false authority", "loss of meaning"),
        "Values become rigid dogma or borrowed certainty, while genuine conviction and independent moral understanding are weakened.",
        None,
        "Sun in Sagittarius as herald and teacher of religious values.",
        29,
    ),
    "THE_LOVERS": CardMetadata(
        ("love", "union", "choice", "commitment", "wholeheartedness"),
        "A heartfelt union or an important choice that asks for sincere commitment rather than half-measures.",
        ("indecision", "division", "disharmony", "avoidance of commitment", "conflicted desire"),
        "The heart is divided, commitment is withheld, or a relationship or decision lacks the inner unity needed to move forward.",
        None,
        "Venus/Jupiter as higher love; Venus/Mars as a decision reached through love.",
        31,
    ),
    "THE_CHARIOT": CardMetadata(
        ("departure", "courage", "independence", "forward movement", "adventure"),
        "A bold departure from familiar surroundings, driven by confidence, freedom, enterprise, and willingness to take one's own path.",
        ("recklessness", "overreach", "arrogance", "loss of direction", "premature action"),
        "Forward movement becomes impulsive or self-important, causing one to outrun experience, preparation, or realistic limits.",
        None,
        "Aries as the awakening of forces.",
        33,
    ),
    "STRENGTH": CardMetadata(
        ("vitality", "passion", "courage", "self-acceptance", "life force"),
        "Vitality, passion, courage, and wholehearted acceptance of instinctive life are integrated into confident action.",
        ("domination", "pride", "uncontrolled passion", "weak confidence", "repression"),
        "Instinct is either repressed or allowed to dominate, producing pride, aggression, insecurity, or loss of inner balance.",
        None,
        "Leo as acceptance of life, vitality, pride, desire, and passion.",
        35,
    ),
    "THE_HERMIT": CardMetadata(
        ("reflection", "wisdom", "independence", "solitude", "inner guidance"),
        "Withdrawal from noise creates the independence and seriousness needed for self-knowledge, maturity, and wise orientation.",
        ("isolation", "withdrawal", "loneliness", "closed-mindedness", "avoidance"),
        "Useful solitude becomes isolation, emotional distance, or retreat from necessary participation and exchange.",
        None,
        "Saturn in Aquarius as the striving for wisdom and preservation of independence.",
        37,
    ),
    "WHEEL_OF_FORTUNE": CardMetadata(
        ("change", "cycle", "fate", "turning point", "development"),
        "A larger cycle is turning; events reveal a developmental necessity that asks for humility, adaptability, and awareness of timing.",
        ("resistance to change", "repetition", "loss of control", "bad timing", "stagnation"),
        "Resistance to the cycle produces repeated patterns, frustrated timing, or the feeling of being carried by events without learning from them.",
        None,
        "Saturn in its role as Lord of Time and teacher.",
        39,
    ),
    "JUSTICE": CardMetadata(
        ("discernment", "fairness", "responsibility", "balance", "truth"),
        "Clear judgment, honesty, balance, and responsibility are required to recognize causes, consequences, and one's own part in the matter.",
        ("bias", "dishonesty", "unfairness", "self-deception", "poor judgment"),
        "Judgment is distorted by prejudice, rationalization, avoidance of responsibility, or an unwillingness to face consequences.",
        None,
        "Jupiter/Mars as power of discernment; Venus in Libra as sincerity and balance.",
        41,
    ),
    "THE_HANGED_MAN": CardMetadata(
        ("suspension", "sacrifice", "reversal of perspective", "surrender", "insight"),
        "Progress requires suspension, surrender, and a deep reversal of perspective before a meaningful change can occur.",
        ("stagnation", "victimhood", "pointless sacrifice", "resistance", "delay"),
        "Necessary surrender is resisted or becomes sterile waiting, self-pity, or sacrifice without insight.",
        None,
        "Pisces as sacrifice and illumination; Sun in the twelfth house as confinement and life change after deep insight.",
        43,
    ),
    "DEATH": CardMetadata(
        ("ending", "release", "transition", "farewell", "transformation"),
        "A genuine ending asks for conscious release of what has completed so that a new phase can become possible.",
        ("clinging", "fear of endings", "stagnation", "incomplete closure", "resistance"),
        "The old is held past its time, creating stagnation, fear, and difficulty making the farewell needed for transformation.",
        None,
        "Saturn in the eighth house: boundary, separation, farewell, death, and growth.",
        45,
    ),
    "TEMPERANCE": CardMetadata(
        ("harmony", "balance", "healing", "moderation", "integration"),
        "Opposites can be reconciled through patience, moderation, balance, and a calm process of integration.",
        ("imbalance", "excess", "impatience", "disharmony", "poor integration"),
        "The harmonizing process is disrupted by extremes, haste, emotional imbalance, or inability to combine opposing needs.",
        None,
        "Venus as harmony and balance.",
        47,
    ),
    "THE_DEVIL": CardMetadata(
        ("bondage", "shadow", "temptation", "dependency", "unintegrated drives"),
        "The card exposes binding forces, compulsions, dependencies, and disowned parts of the personality that require recognition.",
        ("denial", "deepening bondage", "obsession", "projection", "self-deception"),
        "Shadow material remains denied or projected, allowing dependency, compulsion, manipulation, or destructive desire to gain greater power.",
        None,
        "Pluto in its expression as a dark force.",
        49,
    ),
    "THE_TOWER": CardMetadata(
        ("breakthrough", "collapse", "liberation", "sudden change", "truth revealed"),
        "Rigid or false structures break open suddenly, creating disruption but also the possibility of greater freedom and vitality.",
        ("fear of collapse", "resistance", "prolonged crisis", "fragile structures", "suppressed truth"),
        "A necessary breakthrough is resisted, causing tension to accumulate around structures that can no longer remain intact.",
        None,
        "Uranus/Saturn as the sudden breaking through of encrustations.",
        51,
    ),
    "THE_STAR": CardMetadata(
        ("hope", "trust", "vision", "future", "clarity"),
        "Confidence, long-range vision, and a clear sense of future possibility emerge after difficulty.",
        ("discouragement", "short-sightedness", "loss of faith", "poor planning", "disconnection"),
        "Hope or perspective is obscured, making it difficult to see possibilities, trust development, or plan beyond the immediate moment.",
        None,
        "Jupiter in the eleventh house as confidence and long-range vision.",
        53,
    ),
    "THE_MOON": CardMetadata(
        ("uncertainty", "depth", "fear", "unconscious", "descent"),
        "A journey through uncertainty and the deeper layers of the psyche asks for courage where ordinary certainty is unavailable.",
        ("confusion", "anxiety", "deception", "projection", "fear-driven thinking"),
        "Uncertainty becomes disorientation, projection, manipulation, or fear that prevents honest passage through the unknown.",
        None,
        "Moon in Scorpio as hidden wisdom of the soul's depths; Sun in the eighth house as descent into the underworld.",
        55,
    ),
    "THE_SUN": CardMetadata(
        ("joy", "vitality", "success", "warmth", "generosity"),
        "Vitality, generosity, openness, creativity, and sincere enjoyment illuminate the situation and strengthen connection.",
        ("egocentrism", "burnout", "forced optimism", "vanity", "blocked joy"),
        "Radiance becomes self-centered display, exhaustion, superficial optimism, or difficulty allowing genuine joy and warmth.",
        None,
        "Sun in the fifth house as joy of life, creativity, and playful pleasure.",
        57,
    ),
    "JUDGEMENT": CardMetadata(
        ("liberation", "awakening", "redemption", "calling", "decisive breakthrough"),
        "A liberating realization or decisive awakening releases something long constrained and reveals a deeper calling.",
        ("refusal of the call", "self-condemnation", "delay", "fear of change", "missed liberation"),
        "The possibility of liberation is delayed by fear, harsh self-judgment, or refusal to answer what has become unmistakably necessary.",
        None,
        "Jupiter/Uranus in harmonious conjunction with the Sun; Aquarius as liberation and redemption.",
        59,
    ),
    "THE_WORLD": CardMetadata(
        ("completion", "wholeness", "belonging", "fulfillment", "arrival"),
        "A cycle reaches mature completion, bringing a sense of wholeness, belonging, fulfillment, and arrival at the right place.",
        ("incompletion", "unfinished business", "lack of closure", "alienation", "delayed fulfillment"),
        "Completion remains out of reach because something essential is unfinished, unintegrated, or not yet fully accepted.",
        None,
        "Jupiter in Pisces as redemption; Jupiter harmoniously conjunct Saturn as a happy ending.",
        61,
    ),

    # -------------------------
    # WANDS — FIRE
    # -------------------------
    "ACE_OF_WANDS": CardMetadata(
        ("opportunity", "courage", "initiative", "growth", "creative force"),
        "An inner opportunity for courage, initiative, self-development, and energetic creation is ready to be seized.",
        ("hesitation", "wasted potential", "impulsiveness", "low motivation", "misdirected energy"),
        "Creative fire is blocked, squandered, or expressed impulsively without a clear direction.",
        "Fire",
        "Sun/Mars as courage, determination, willingness to take risks, and the force of self-development.",
        63,
    ),
    "TWO_OF_WANDS": CardMetadata(
        ("planning", "distance", "neutrality", "consideration", "potential choice"),
        "A position of observation and planning exists, but commitment has not yet moved from theory into lived action.",
        ("indecision", "detachment", "fear of commitment", "passivity", "empty planning"),
        "Thinking substitutes for commitment, leaving the situation suspended in indecision or emotional disengagement.",
        "Fire",
        "Mars in Libra as a theoretical decision without inner engagement or practical consequences.",
        65,
    ),
    "THREE_OF_WANDS": CardMetadata(
        ("confidence", "foresight", "foundation", "expansion", "reliability"),
        "A secure foundation supports confidence, long-range planning, and constructive expansion.",
        ("poor foresight", "weak foundation", "overconfidence", "delay", "limited outlook"),
        "Expansion is compromised by insufficient preparation, narrow vision, or confidence that exceeds the actual foundation.",
        "Fire",
        "Mercury in Leo as confidence and long-range vision; harmonious with Saturn as a basis of reliability.",
        67,
    ),
    "FOUR_OF_WANDS": CardMetadata(
        ("celebration", "openness", "community", "security", "joy"),
        "A protected and sociable space encourages celebration, openness, companionship, and shared enjoyment.",
        ("social tension", "instability", "isolation", "awkward celebration", "lack of belonging"),
        "The promise of community or celebration is weakened by instability, exclusion, or difficulty relaxing into shared joy.",
        "Fire",
        "Venus in the fifth house as joy, amusement, and pleasure; Moon/Venus as security and sociability.",
        69,
    ),
    "FIVE_OF_WANDS": CardMetadata(
        ("competition", "challenge", "testing", "playful conflict", "effort"),
        "A lively challenge tests strength and skill through competition, friction, and active engagement.",
        ("pointless conflict", "hostility", "avoidance of challenge", "ego clashes", "chaos"),
        "Healthy competition becomes wasteful conflict, or challenge is avoided because disagreement feels threatening.",
        "Fire",
        "Mars in the fifth house as sporting competition.",
        71,
    ),
    "SIX_OF_WANDS": CardMetadata(
        ("victory", "recognition", "success", "confidence", "good news"),
        "Effort receives recognition and success, strengthening confidence and the sense that progress is visible to others.",
        ("empty praise", "setback", "arrogance", "lack of recognition", "fragile confidence"),
        "Recognition is delayed, exaggerated, or used to feed pride rather than support genuine achievement.",
        "Fire",
        "Jupiter in the tenth house as success and recognition.",
        73,
    ),
    "SEVEN_OF_WANDS": CardMetadata(
        ("defense", "advantage", "courage", "resistance", "assertiveness"),
        "A favorable position can be defended through alertness, skill, courage, and firm boundaries.",
        ("overwhelm", "defensiveness", "giving up", "paranoia", "poor boundaries"),
        "Pressure produces chronic defensiveness, exhaustion, or retreat from a position that still requires conscious protection.",
        "Fire",
        "Mercury/Mars in aspect with Saturn as skillful struggle against an obstacle.",
        75,
    ),
    "EIGHT_OF_WANDS": CardMetadata(
        ("movement", "acceleration", "news", "timing", "developments"),
        "Events gather speed and important developments approach; timing and responsiveness become central.",
        ("delay", "scattered movement", "miscommunication", "poor timing", "stalled momentum"),
        "Movement loses coordination through delays, premature action, crossed signals, or failure to recognize the right moment.",
        "Fire",
        "The time factor in astrological prognosis: activating transits, directions, progressions, rhythms, and related timing factors.",
        77,
    ),
    "NINE_OF_WANDS": CardMetadata(
        ("defense", "persistence", "wariness", "resilience", "protection"),
        "Past strain has produced caution and defensive readiness; perseverance is needed without retreating from hard-won ground.",
        ("hypervigilance", "exhaustion", "fear", "retreat", "rigidity"),
        "Protection becomes a prison of suspicion, fatigue, or fear of repeating earlier pain.",
        "Fire",
        "Saturn/Venus as armor and defensive attitude.",
        79,
    ),
    "TEN_OF_WANDS": CardMetadata(
        ("burden", "pressure", "responsibility", "overload", "endurance"),
        "The situation is weighed down by heavy responsibility, pressure, and a constricted sense of possibility.",
        ("collapse", "refusal to delegate", "burnout", "avoidance of responsibility", "release"),
        "The burden has become unsustainable, or responsibility is mishandled through overcontrol, avoidance, or inability to share the load.",
        "Fire",
        "Saturn/Sun as weight and oppression; or Saturn in the eleventh house as lack of perspective.",
        81,
    ),
    "PAGE_OF_WANDS": CardMetadata(
        ("opportunity", "invitation", "enthusiasm", "adventure", "new impulse"),
        "An external opportunity, invitation, or inspiring impulse appears and asks for courage and enthusiasm.",
        ("missed opportunity", "immaturity", "empty excitement", "fear", "false start"),
        "An opportunity is ignored, exaggerated, or approached with enthusiasm that lacks readiness and follow-through.",
        "Fire",
        "Venus conjunct Moon in Sagittarius as an opportunity seized with enthusiasm.",
        83,
    ),
    "KNIGHT_OF_WANDS": CardMetadata(
        ("adventure", "initiative", "passion", "movement", "impatience"),
        "A fiery state of mind seeks action, adventure, movement, and immediate engagement with life.",
        ("recklessness", "aggression", "restlessness", "impatience", "instability"),
        "Drive becomes volatile, aggressive, impatient, or unable to remain with a course long enough to mature.",
        "Fire",
        "Mars in Aries as initiative, desire for action, temperament, adventurous spirit, and impatience.",
        85,
    ),
    "QUEEN_OF_WANDS": CardMetadata(
        ("confidence", "warmth", "independence", "vitality", "pride"),
        "Fire appears in a receptive form as warmth, confidence, vitality, independence, and passionate engagement with life.",
        ("jealousy", "domineering pride", "insecurity", "temper", "self-absorption"),
        "Confidence is undermined by insecurity or distorted into pride, jealousy, theatricality, or emotional domination.",
        "Fire",
        "Moon in Leo as love of life, temperament, pride, self-confidence, and indomitability.",
        87,
    ),
    "KING_OF_WANDS": CardMetadata(
        ("leadership", "sovereignty", "confidence", "generosity", "vision"),
        "Fire in an active form expresses mature leadership, confidence, generosity, conviction, and the ability to inspire.",
        ("authoritarianism", "arrogance", "domination", "impulsiveness", "ego"),
        "Leadership becomes self-important, domineering, impatient, or more concerned with personal authority than the larger purpose.",
        "Fire",
        "Sun in Leo as self-confidence and sovereignty.",
        89,
    ),

    # -------------------------
    # SWORDS — AIR
    # -------------------------
    "ACE_OF_SWORDS": CardMetadata(
        ("clarity", "decision", "insight", "discernment", "truth"),
        "An inner opportunity for clear thought, decisive understanding, and the ability to cut through confusion.",
        ("confusion", "harsh judgment", "misuse of intellect", "indecision", "mental rigidity"),
        "The sword of discernment becomes blunt or destructive through confusion, coldness, premature conclusions, or intellectual aggression.",
        "Air",
        "Mercury/Mars as acuity and power of decision; Mercury/Jupiter as gain of knowledge and higher reason.",
        91,
    ),
    "TWO_OF_SWORDS": CardMetadata(
        ("doubt", "stalemate", "skepticism", "inner conflict", "suspension"),
        "Deep inner doubt creates a suspended state in which judgment remains guarded and commitment is difficult.",
        ("denial", "confusion", "forced decision", "avoidance", "mental overload"),
        "The stalemate is prolonged through denial or broken prematurely by a decision made without resolving the underlying conflict.",
        "Air",
        "Moon in Gemini as deep inner doubt.",
        93,
    ),
    "THREE_OF_SWORDS": CardMetadata(
        ("painful truth", "heartbreak", "decision", "separation", "conflict"),
        "A painful realization or decision cuts against feeling, bringing sorrow but also uncompromising clarity.",
        ("lingering hurt", "resentment", "emotional denial", "cruelty", "unresolved grief"),
        "Pain is suppressed, prolonged, or weaponized, preventing the difficult truth from becoming constructive understanding.",
        "Air",
        "Mars/Moon as wounded feelings; with Mercury as a decision made against feeling.",
        95,
    ),
    "FOUR_OF_SWORDS": CardMetadata(
        ("pause", "rest", "inactivity", "recovery", "withdrawal"),
        "Activity is blocked or suspended, calling for retreat, recovery, waiting, or acceptance of a temporary standstill.",
        ("restlessness", "burnout", "stagnation", "premature return", "forced inactivity"),
        "Rest is resisted or extended beyond usefulness, creating exhaustion, frustration, or sterile inactivity.",
        "Air",
        "Saturn in the fifth house as blocked creativity, or in the sixth house as an indication of illness.",
        97,
    ),
    "FIVE_OF_SWORDS": CardMetadata(
        ("conflict", "defeat", "hostility", "humiliation", "destruction"),
        "Conflict has become destructive and can produce defeat, humiliation, betrayal, or a victory whose cost is too high.",
        ("revenge", "prolonged hostility", "refusal to reconcile", "shame", "damage control"),
        "The destructive conflict continues through resentment and revenge, or the aftermath is avoided rather than repaired.",
        "Air",
        "Mars in Scorpio in its ominous expression as destructive force and perfidy.",
        99,
    ),
    "SIX_OF_SWORDS": CardMetadata(
        ("departure", "transition", "new horizons", "journey", "uncertainty"),
        "A necessary departure moves away from familiar territory toward new horizons, even when the destination is not yet fully known.",
        ("resistance to transition", "unfinished departure", "fear of the unknown", "returning", "delay"),
        "The move forward is resisted or repeatedly interrupted by attachment to the familiar and fear of what lies ahead.",
        "Air",
        "Mars in the fourth house as departure from the familiar environment; Mercury in the ninth house as search for new horizons.",
        101,
    ),
    "SEVEN_OF_SWORDS": CardMetadata(
        ("cunning", "deception", "strategy", "evasion", "cleverness"),
        "Intelligence is used indirectly through strategy, concealment, evasion, or cunning, with a strong warning about dishonesty.",
        ("self-deception", "exposure", "bad strategy", "guilt", "failed deception"),
        "Cleverness collapses into self-deception or exposure, and evasive strategies become harder to sustain.",
        "Air",
        "Mercury as cunning, imposture, pettiness, and falsehood.",
        103,
    ),
    "EIGHT_OF_SWORDS": CardMetadata(
        ("inhibition", "restriction", "self-limitation", "fear", "blocked expression"),
        "An important part of the self is being inhibited by internal prohibitions that are projected outward as external impossibility.",
        ("release", "recognizing options", "persistent fear", "self-sabotage", "mental prison"),
        "The inner restriction is either beginning to loosen or remains entrenched through self-sabotage and fear-based assumptions.",
        "Air",
        "Saturn in the fourth house as inner inhibition.",
        105,
    ),
    "NINE_OF_SWORDS": CardMetadata(
        ("anxiety", "guilt", "worry", "remorse", "night thoughts"),
        "Fear, guilt, remorse, and oppressive worry dominate the mental field and require honest acknowledgment rather than concealment.",
        ("spiraling anxiety", "shame", "denial", "recovery", "release of guilt"),
        "Worry either intensifies through secrecy and self-punishment or begins to ease as guilt and fear are consciously faced.",
        "Air",
        "Saturn/Moon as worry, oppression, and guilt.",
        107,
    ),
    "TEN_OF_SWORDS": CardMetadata(
        ("ending", "finality", "collapse", "severance", "painful conclusion"),
        "A harsh or deliberate ending closes a chapter decisively and creates space for something fundamentally different.",
        ("refusal to end", "prolonged collapse", "victimhood", "partial recovery", "resistance"),
        "The ending is prolonged through resistance, repeated injury, or unwillingness to accept that the old form has reached its limit.",
        "Air",
        "Mars/Saturn as an arbitrary and violent end.",
        109,
    ),
    "PAGE_OF_SWORDS": CardMetadata(
        ("challenge", "criticism", "message", "provocation", "mental test"),
        "An external challenge, criticism, or provocative message tests clarity and invites a more alert, discriminating response.",
        ("gossip", "needless conflict", "defensiveness", "misinformation", "provocation"),
        "The challenge degenerates into gossip, needless argument, suspicion, or reacting before facts are understood.",
        "Air",
        "Mars in the third house, or in challenging aspect with Mercury, as the sowing of discord and disunity.",
        111,
    ),
    "KNIGHT_OF_SWORDS": CardMetadata(
        ("confrontation", "cold reason", "decisiveness", "severity", "intellectual force"),
        "A sharp, confrontational mental atmosphere demands speed, rational rigor, and the willingness to cut through sentiment.",
        ("aggression", "cruelty", "rashness", "hostility", "verbal violence"),
        "Reason becomes merciless or impulsive, producing conflict, harshness, and action taken faster than understanding.",
        "Air",
        "Saturn/Venus as coldness and severity in relationships and contacts; Mars/Mercury as rigor of reason and confrontation.",
        113,
    ),
    "QUEEN_OF_SWORDS": CardMetadata(
        ("independence", "discernment", "individuality", "clarity", "wisdom"),
        "Air in a receptive form expresses independence, intelligent distance, individuality, and clear perception.",
        ("bitterness", "detachment", "cynicism", "coldness", "isolation"),
        "Independence hardens into emotional coldness, cynicism, isolation, or judgment without compassion.",
        "Air",
        "Sun in Aquarius as independence, individuality, and wise knowledge.",
        115,
    ),
    "KING_OF_SWORDS": CardMetadata(
        ("intellect", "strategy", "versatility", "authority", "cleverness"),
        "Air in an active form expresses intellectual command, strategic skill, versatility, and sharp judgment.",
        ("manipulation", "cold authority", "cunning", "sarcasm", "intellectual domination"),
        "Mental power is used manipulatively or without empathy, turning intelligence into cold control or calculated self-interest.",
        "Air",
        "Mercury in Gemini as wit, versatility, cunning, and shrewdness.",
        117,
    ),

    # -------------------------
    # PENTACLES — EARTH
    # -------------------------
    "ACE_OF_PENTACLES": CardMetadata(
        ("opportunity", "prosperity", "value", "security", "tangible potential"),
        "An inner opportunity for tangible well-being, security, material value, and lasting fulfillment is present.",
        ("missed opportunity", "material fixation", "insecurity", "poor foundation", "waste"),
        "A valuable chance is overlooked, mishandled, or reduced to narrow materialism and fear of scarcity.",
        "Earth",
        "Venus in the second house as the chance for inner and outer happiness and wealth.",
        119,
    ),
    "TWO_OF_PENTACLES": CardMetadata(
        ("adaptability", "playfulness", "flexibility", "change", "juggling"),
        "Fluid adaptation and lightness allow changing circumstances to be handled without becoming overly fixed or solemn.",
        ("instability", "carelessness", "overextension", "inconsistency", "poor priorities"),
        "Flexibility becomes unreliability, superficiality, or inability to establish stable priorities.",
        "Earth",
        "Moon on the Ascendant as fluid adaptability; Moon/Mars as inconstancy.",
        121,
    ),
    "THREE_OF_PENTACLES": CardMetadata(
        ("mastery", "learning", "achievement", "qualification", "new stage"),
        "A stage of competent achievement is reached through learning, practice, and entry into a more demanding level of development.",
        ("poor workmanship", "lack of learning", "mediocrity", "unpreparedness", "stalled progress"),
        "Growth is blocked by inadequate preparation, unwillingness to learn, or failure to meet the standards of the next stage.",
        "Earth",
        "Jupiter/Mars as successful achievement; or Saturn returning to its natal position as entry into a new phase of life.",
        123,
    ),
    "FOUR_OF_PENTACLES": CardMetadata(
        ("security", "holding", "possession", "control", "stability"),
        "The need for security becomes central, emphasizing preservation, boundaries, and the wish to hold what has been acquired.",
        ("possessiveness", "fear of loss", "greed", "rigidity", "hoarding"),
        "Security turns obsessive, producing possessiveness, rigidity, fear of risk, or inability to let resources circulate.",
        "Earth",
        "Saturn in the second house as an obsessive need for security.",
        125,
    ),
    "FIVE_OF_PENTACLES": CardMetadata(
        ("crisis", "scarcity", "hardship", "exclusion", "need for help"),
        "A period of material or emotional hardship exposes limits and makes support, humility, and realistic endurance important.",
        ("isolation", "shame", "refusal of help", "prolonged scarcity", "recovery"),
        "Hardship worsens through isolation or shame, or begins to ease when help and connection are finally accepted.",
        "Earth",
        "Saturn in the second house as crisis and obstacles.",
        127,
    ),
    "SIX_OF_PENTACLES": CardMetadata(
        ("generosity", "support", "giving", "receiving", "fair exchange"),
        "Resources, assistance, and generosity can circulate constructively through willingness both to help and to receive help.",
        ("strings attached", "dependency", "inequality", "withholding", "misused generosity"),
        "Giving and receiving become unequal, controlling, conditional, or distorted by dependency and pride.",
        "Earth",
        "Jupiter in Pisces as willingness to help; Jupiter in Leo as generosity; Jupiter in Aquarius as tolerance.",
        129,
    ),
    "SEVEN_OF_PENTACLES": CardMetadata(
        ("patience", "growth", "waiting", "cultivation", "long-term development"),
        "Growth is slow but reliable and asks for patience, cultivation, and trust in processes that cannot be forced.",
        ("impatience", "poor return", "abandonment", "stagnation", "premature action"),
        "The process is disrupted by impatience, discouragement, or abandoning something before its natural development can mature.",
        "Earth",
        "Jupiter/Saturn as patience and slow but secure growth.",
        131,
    ),
    "EIGHT_OF_PENTACLES": CardMetadata(
        ("learning", "practice", "skill", "craftsmanship", "discipline"),
        "Skill develops through practice, study, repetition, and humble willingness to learn.",
        ("perfectionism", "monotony", "poor workmanship", "lack of discipline", "stagnant learning"),
        "Practice becomes mechanical or perfectionistic, or progress stalls because discipline and genuine learning are missing.",
        "Earth",
        "Mercury in the third house as learning and skill.",
        133,
    ),
    "NINE_OF_PENTACLES": CardMetadata(
        ("gain", "enjoyment", "success", "reward", "self-sufficiency"),
        "A favorable phase brings tangible reward, enjoyment, confidence, and the ability to appreciate what has been cultivated.",
        ("overindulgence", "dependency", "fragile success", "waste", "isolation in comfort"),
        "Material comfort is poorly used, becomes excessive, or hides dependence and insecurity beneath an appearance of success.",
        "Earth",
        "Jupiter/Venus in the fifth house as great gain.",
        135,
    ),
    "TEN_OF_PENTACLES": CardMetadata(
        ("wealth", "legacy", "stability", "abundance", "long-term security"),
        "Material and relational structures reach a state of richness, continuity, and durable security.",
        ("family burden", "unstable legacy", "materialism", "loss", "rigid tradition"),
        "What should provide continuity becomes constricting, materially fixated, unstable, or burdened by inherited expectations.",
        "Earth",
        "Jupiter in the second house as fullness and wealth.",
        137,
    ),
    "PAGE_OF_PENTACLES": CardMetadata(
        ("valuable opportunity", "practical offer", "learning", "support", "potential"),
        "A valuable external opportunity or practical offer appears and deserves careful, grounded attention.",
        ("missed chance", "poor planning", "lack of commitment", "naivety", "unrealistic offer"),
        "A promising opportunity is overlooked or approached without the patience, realism, or commitment required to make it useful.",
        "Earth",
        "Uranus and Venus combined with Taurus as a surprising and valuable opportunity.",
        139,
    ),
    "KNIGHT_OF_PENTACLES": CardMetadata(
        ("reliability", "patience", "persistence", "solid values", "steady progress"),
        "A steady, reliable mood favors patient effort, practical responsibility, and growth built on established values.",
        ("stubbornness", "stagnation", "routine", "overcaution", "material rigidity"),
        "Reliability hardens into inflexibility, overcaution, dull routine, or resistance to necessary change.",
        "Earth",
        "Jupiter in Taurus as stable, solid, already developed values.",
        141,
    ),
    "QUEEN_OF_PENTACLES": CardMetadata(
        ("groundedness", "fertility", "care", "practicality", "security"),
        "Earth in a receptive form expresses grounded care, fertility, practical intelligence, patience, and a strong sense of home and reality.",
        ("smothering", "material anxiety", "overprotection", "neglect of self", "possessiveness"),
        "Care becomes overprotective or anxious, or practical responsibilities consume the space needed for personal vitality.",
        "Earth",
        "Moon in Taurus as rootedness, fertility, and family sense.",
        143,
    ),
    "KING_OF_PENTACLES": CardMetadata(
        ("stability", "sensuality", "prosperity", "practical authority", "stewardship"),
        "Earth in an active form expresses practical authority, stable values, enjoyment of life, and skill in managing tangible resources.",
        ("greed", "stubbornness", "materialism", "control", "complacency"),
        "Material mastery becomes possessiveness, complacency, rigid control, or measuring value too narrowly through ownership and comfort.",
        "Earth",
        "Sun in Taurus as striving for possession, sensory pleasure, and awareness of the relativity of things.",
        145,
    ),

    # -------------------------
    # CUPS — WATER
    # -------------------------
    "ACE_OF_CUPS": CardMetadata(
        ("fulfillment", "love", "grace", "emotional opening", "blessing"),
        "An inner opening toward deep emotional fulfillment, love, reconciliation, and heartfelt connection is available.",
        ("emotional blockage", "emptiness", "withheld affection", "dependency", "overflow"),
        "Feeling is blocked, withheld, or overwhelming, making genuine emotional exchange difficult.",
        "Water",
        "Neptune/Jupiter in harmonious combination with the Sun as the blessing of deep fulfillment.",
        147,
    ),
    "TWO_OF_CUPS": CardMetadata(
        ("union", "reciprocity", "affection", "reconciliation", "partnership"),
        "Mutual affection, welcome, reconciliation, or a new bond creates a genuinely reciprocal connection.",
        ("disharmony", "separation", "one-sidedness", "broken trust", "poor reciprocity"),
        "The bond loses reciprocity through emotional imbalance, estrangement, or difficulty meeting each other openly.",
        "Water",
        "Venus on the Ascendant as loving involvement.",
        149,
    ),
    "THREE_OF_CUPS": CardMetadata(
        ("joy", "celebration", "friendship", "gratitude", "community"),
        "Shared joy, gratitude, friendship, and celebration strengthen emotional connection and social belonging.",
        ("excess", "superficiality", "social tension", "gossip", "overindulgence"),
        "Celebration loses depth through excess, superficiality, exclusion, or social dynamics that undermine trust.",
        "Water",
        "Venus as cheerfulness and gratitude.",
        151,
    ),
    "FOUR_OF_CUPS": CardMetadata(
        ("discontent", "boredom", "withdrawal", "irritation", "emotional refusal"),
        "Emotional dissatisfaction or bad temper narrows attention and makes it difficult to recognize what is still being offered.",
        ("apathy", "chronic dissatisfaction", "reopening", "restlessness", "re-engagement"),
        "Discontent becomes entrenched apathy, or the emotional withdrawal begins to loosen enough for renewed engagement.",
        "Water",
        "Mars in Cancer as annoyance and bad temper.",
        153,
    ),
    "FIVE_OF_CUPS": CardMetadata(
        ("grief", "loss", "bitterness", "sadness", "support"),
        "A real loss brings grief, bitterness, and melancholy, while also revealing the importance of accepting empathy and support.",
        ("stuck grief", "self-blame", "isolation", "healing", "acceptance"),
        "Grief is prolonged by isolation or self-reproach, or begins to transform as support and acceptance become possible.",
        "Water",
        "Saturn/Venus or Saturn/Moon as farewell, pain, bitterness, and depression.",
        155,
    ),
    "SIX_OF_CUPS": CardMetadata(
        ("memory", "nostalgia", "tenderness", "past", "romance"),
        "Memories, nostalgia, tenderness, and the emotional pull of the past shape the present experience.",
        ("idealized past", "regression", "melancholy", "difficulty moving on", "nostalgic distortion"),
        "The past is idealized or used as refuge, preventing present reality from being encountered on its own terms.",
        "Water",
        "Moon in Pisces as wistful and melancholic memories; Moon in Cancer as dreamy romanticism.",
        157,
    ),
    "SEVEN_OF_CUPS": CardMetadata(
        ("illusion", "fantasy", "temptation", "false hopes", "many possibilities"),
        "A profusion of images and possibilities can become illusion; clarity requires distinguishing realistic aims from seductive fantasies.",
        ("disillusionment", "confusion", "escapism", "clarifying choice", "deception"),
        "Fantasy either intensifies into escapism and deception or collapses into the clarifying disappointment needed to choose realistically.",
        "Water",
        "Neptune as illusion, mirages, and escape from reality.",
        159,
    ),
    "EIGHT_OF_CUPS": CardMetadata(
        ("departure", "farewell", "sadness", "leaving behind", "emotional transition"),
        "A sorrowful but necessary departure asks for leaving something emotionally significant behind.",
        ("fear of leaving", "returning", "avoidance", "unfinished goodbye", "emotional stagnation"),
        "The farewell is resisted, repeatedly reversed, or avoided even though the old emotional situation no longer provides a viable path.",
        "Water",
        "Saturn/Moon as sorrowful farewell.",
        161,
    ),
    "NINE_OF_CUPS": CardMetadata(
        ("pleasure", "sociability", "enjoyment", "satisfaction", "hospitality"),
        "A pleasurable phase invites enjoyment, sociability, gratitude, and appreciation of life's comforts.",
        ("overindulgence", "complacency", "empty pleasure", "self-satisfaction", "excess"),
        "Pleasure becomes excessive, self-satisfied, or disconnected from deeper emotional needs.",
        "Water",
        "Moon in Taurus as pleasure and sociability.",
        163,
    ),
    "TEN_OF_CUPS": CardMetadata(
        ("harmony", "belonging", "family joy", "protection", "emotional fulfillment"),
        "Emotional closeness, harmony, protection, and shared belonging create a deeply supportive atmosphere.",
        ("family tension", "disharmony", "idealization", "alienation", "broken belonging"),
        "The ideal of harmony conflicts with lived reality, producing tension, exclusion, or pressure to preserve appearances.",
        "Water",
        "Jupiter/Moon as protection and happy closeness.",
        165,
    ),
    "PAGE_OF_CUPS": CardMetadata(
        ("reconciliation", "kind gesture", "invitation", "affection", "emotional opportunity"),
        "An external emotional opportunity arrives through a kind gesture, invitation, reconciliation, or playful affectionate contact.",
        ("emotional immaturity", "mixed signals", "missed invitation", "naivety", "insincerity"),
        "The emotional offer is misunderstood, immature, inconsistent, or not taken seriously enough to become meaningful.",
        "Water",
        "Venus in the first house as a reconciliatory impulse, or in the fifth house as cheerful pleasure.",
        167,
    ),
    "KNIGHT_OF_CUPS": CardMetadata(
        ("romance", "peace", "tenderness", "reconciliation", "dreaminess"),
        "A gentle emotional atmosphere favors reconciliation, romance, contemplation, beauty, and the wisdom of a softer response.",
        ("idealization", "moodiness", "escapism", "sentimentality", "unreliable emotion"),
        "Tenderness becomes idealization, sentimentality, escapism, or moods too changeable to support reliable action.",
        "Water",
        "Venus/Moon as tenderness and good humor.",
        169,
    ),
    "QUEEN_OF_CUPS": CardMetadata(
        ("sensitivity", "empathy", "intuition", "care", "receptivity"),
        "Water in a receptive form expresses empathy, sensitivity, intuitive understanding, and readiness to help.",
        ("emotional absorption", "dependency", "confusion", "over-sensitivity", "poor boundaries"),
        "Sensitivity loses boundaries and becomes emotional absorption, dependency, confusion, or vulnerability to others' moods.",
        "Water",
        "Moon in Pisces as sensitivity, willingness to help, and mediumistic receptivity.",
        171,
    ),
    "KING_OF_CUPS": CardMetadata(
        ("emotional wisdom", "compassion", "maturity", "intuition", "support"),
        "Water in an active form expresses mature emotional wisdom, instinctive understanding, compassion, and the capacity to support others.",
        ("emotional control", "suppression", "manipulation", "detachment", "hidden volatility"),
        "Emotional mastery becomes suppression, subtle manipulation, detachment, or concealed volatility.",
        "Water",
        "Sun in Pisces as mediumistic receptivity, instinctive wisdom, and willingness to help.",
        173,
    ),
}
